Update release action workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: 'Draft Release v1.0.0'
+name: 'Draft Release v1.0.1'
 
 on:
   push:
@@ -19,9 +19,11 @@ jobs:
     with:
       TAG: ${{ github.ref_name }}
   release:
-    name: Create Release Draft
+    name: Create release draft
     needs: [linux, windows, macos]
     runs-on: ubuntu-latest
+    outputs:
+      changelog-section: ${{ steps.extract.outputs.changelog_section }}
     permissions:
       contents: write
     steps:
@@ -46,17 +48,41 @@ jobs:
           name: jwlFusion-windows.zip
           path: dist/windows
 
-      - name: Extract release notes
-        id: extract-release-notes
-        uses: ffurrer2/extract-release-notes@v2
+      - name: Extract section from changelog
+        id: extract
+        env:
+          CHANGELOG_FILE: "CHANGELOG.md"
+        run: |
+          if [[ ! -f "$CHANGELOG_FILE" ]]; then
+            echo "Error: File '$CHANGELOG_FILE' not found!"
+            exit 1
+          fi
+          changelog_section=$(awk '
+          /^## / { h2_count++ } 
+          h2_count == 2 && !/^## / && !/^$/ { in_section = 1 } 
+          h2_count == 3 { in_section = 0 } 
+          in_section { 
+              if (/^[[:space:]]*$/) { 
+                  empty_buffer = empty_buffer $0 "\n" 
+              } else { 
+                  printf "%s", empty_buffer 
+                  empty_buffer = "" 
+                  print 
+              } 
+          }
+          ' "$CHANGELOG_FILE")
+          echo "changelog_section<<EOF" >> $GITHUB_OUTPUT
+          echo "$changelog_section" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
 
       - name: Create release
         uses: softprops/action-gh-release@v2
         with:
           tag_name: ${{ github.ref_name }}
           name: ${{ github.ref_name }}
+          draft: true
           body: |
-            ${{ steps.extract-release-notes.outputs.release_notes }}
+            ${{ steps.extract.outputs.changelog_section }}
           files: |
             dist/linux/jwlFusion-linux.tgz
             dist/macos/jwlFusion-macos.tar.gz
