Update test workflow

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -12,21 +12,45 @@ jobs:
   release:
     name: Create release draft
     runs-on: ubuntu-latest
+    outputs:
+      changelog-section: ${{ steps.extract.outputs.changelog_section }}
     permissions:
       contents: write
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Extract release notes
-        id: extract-release-notes
-        uses: ffurrer2/extract-release-notes@v2
-        with:
-          release_notes_file: ${{ github.workspace }}-CHANGELOG.txt
+      - name: Extract section from changelog
+        id: extract
+        env:
+          CHANGELOG_FILE: "CHANGELOG.md"
+        run: |
+          if [[ ! -f "$CHANGELOG_FILE" ]]; then
+            echo "Error: File '$CHANGELOG_FILE' not found!"
+            exit 1
+          fi
+          changelog_section=$(awk '
+          /^## / { h2_count++ } 
+          h2_count == 2 && !/^## / && !/^$/ { in_section = 1 } 
+          h2_count == 3 { in_section = 0 } 
+          in_section { 
+              if (/^[[:space:]]*$/) { 
+                  empty_buffer = empty_buffer $0 "\n" 
+              } else { 
+                  printf "%s", empty_buffer 
+                  empty_buffer = "" 
+                  print 
+              } 
+          }
+          ' "$CHANGELOG_FILE")
+          echo "changelog_section<<EOF" >> $GITHUB_OUTPUT
+          echo "$changelog_section" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
 
-      - name: Debug release notes
-        run: echo "${{ steps.extract-release-notes.outputs.release_notes }}"
-
+      - name: Use the extracted section
+        run: |
+          echo "Extracted section:"
+          echo "${{ steps.extract.outputs.changelog_section }}"
 
       - name: Create release
         uses: softprops/action-gh-release@v2
@@ -34,5 +58,7 @@ jobs:
           tag_name: ${{ inputs.TAG }}
           name: ${{ inputs.TAG }}
           draft: true
-          body_path: ${{ github.workspace }}-CHANGELOG.txt
-
+          body: |
+            ${{ steps.extract.outputs.changelog_section }}
+            ____
+            This is a test
